package mutua.events;

/** <pre>
 * Event.java
 * ==========
 * (created by luiz, Jan 23, 2015)
 *
 * Represents an event generated by an 'EventServer', able to be serialized and executed by an 'EventClient' 
 *
 * @see EventClient, EventServer
 * @version $Id$
 * @author luiz
 */

public class Event {
	
	private final Object serviceId;
	private final Object[] parameters;
	
	public Event(Object serviceId, Object[] parameters) {
		this.serviceId  = serviceId;
		this.parameters = parameters;
	}
	
	public Object getServiceId() {
		return serviceId;
	}
	
	public Object[] getParameters() {
		return parameters;
	}

}
